### PR TITLE
Stateful account management

### PR DESCRIPTION
**Pull request by kernelkind**
See attached video for demonstration

https://github.com/user-attachments/assets/081ab112-a616-4784-8b31-d2c87b0ff335

### CODE REVIEW

**Comment by jb55** [comment]
for some reason it flickers when you click the switch button?

**Comment by jb55** [comment]
oh maybe this is just a preview thing? because of `show_account_switcher = false` after the `SelectAccount` action? The window is supposed to close after selection?

**Comment by jb55** [comment]
looks good at a high level, I will try to integrate it... it's weird to review when its only in previews so I'm not sure if its working or not

**Comment by kernelkind** [comment]
The issue i was returning early when it detected a switch was happening. Should be fixed now

**Comment by kernelkind** [comment]
> oh maybe this is just a preview thing? because of `show_account_switcher = false` after the `SelectAccount` action? The window is supposed to close after selection?

Right now the window is not supposed to close after selection. Also there isn't integration with the account switcher yet because we don't have temporary columns yet.

I was imagining that the closure of the column would happen by the column itself but if we want the widget inside the temporary column to send signals to the column to close I think they should send a response to the column and the column can do that itself

**Comment by kernelkind** [comment]
stopped using my fork for `egui-nav` since my PR got merged. Also did `cargo update`

**Comment by kernelkind** [comment]
rebase with master

**Comment by jb55** [comment]
I rebased this on my refactor branch. I think we can drop the RoutableWidgetState now, since routes are stored in columns

**Comment by jb55** [comment]
I'll continue hacking on this to trim it down

**Comment by jb55** [comment]
> I think we can drop the RoutableWidgetState now

actually I may call this Router<Route> and eventually integrate this back into egui-nav (maybe). The returning and navigating states should probably be handled in there.

**Comment by jb55** [comment]
this is merged in master with a bunch of changes. I am going to work on pushing account management as a route on the first timeline

**Pull request closed without merging**
