### PR TITLE
Integrate sidebar

### PR DESCRIPTION
**Pull request by jb55**
This follows from:

- #76 

It hooks up the sidebar into our UI, but we still need to make the buttons work and implement a design:

- #77

### CODE REVIEW

**Comment by kernelkind** [comment]
Run `./preview DesktopGlobalPopup` to see an example with accounts populated. I didn't change the `StateInMemory` (formerly `PersistedState`) conception yet to not use static IDs because I can't think of a better solution yet. Let me know what you think @jb55

**Comment by jb55** [comment]
let's not merge mased into this, I will rebase it

**Comment by jb55** [comment]
see `git range-diff 1b0de88173c9...df0377cb891c` for rebase diff

**Comment by jb55** [comment]
all this will need to be refactored. There is too much global state everywhere, and many of the components are needlessly touching global state when they can simply return individual responses. I will start on this refactoring to show what I mean. ideally don't do any more work on this branch until we get this sorted.

**Comment by jb55** [comment]
I'm happy the state this is in for now, even if the sidebar is non-functional. We have click handling states at least! Wanted to merge this since there are a bunch of changes and I don't want this to get too out of sync with master.

Working on nav so that we can re-add the global popup.

**Pull request merged**
