### PR TITLE
use hashtag icon

### PR DESCRIPTION
**Pull request by kernelkind**
closes https://github.com/damus-io/notedeck/issues/490

### CODE REVIEW

**Comment by jb55** [comment]
we should update the column title icon as well, right now its just an empty pfp

**Comment by kernelkind** [comment]
> we should update the column title icon as well, right now its just an empty pfp

which column title? Add Column?

**Comment by jb55** [comment]
On Mon, Dec 23, 2024 at 07:23:09AM -0800, kernelkind wrote:
>> we should update the column title icon as well, right now its just an empty pfp
>
>which column title? Add Column?

hashtag column header

**Comment by jb55** [comment]
thanks!

**Pull request merged**
