### PR TITLE
Full Decks Support

### PR DESCRIPTION
**Pull request by kernelkind**
Adds the intended Decks implementation including UI elements

### CODE REVIEW

**Comment by kernelkind** [comment]
https://github.com/user-attachments/assets/db45a365-3069-4dcc-9a9f-8e80ca4f05db

deck switching progress

**Comment by kernelkind** [comment]
# Minimum Viable Product Decks
Features walkthrough:
https://github.com/user-attachments/assets/f07b8115-a66f-4386-a998-5ec7a37a2abf

Right click the deck icon in the side panel to edit the deck. This is temporary, so I didn't need to create the expanded side panel

Can do the following:
- create new deck
- switch decks
- edit deck name
- delete decks
- switch to new account and do all of the above

**Comment by jb55** [comment]
this breaks cli arguments again. we should have tests for those...

**Comment by jb55** [comment]
reproduce:

```
./target/release/notedeck --no-keystore --sec $JB55_SEC --sec $DAMUS_SEC -c contacts -c notifications -c notifications:$DAMUS -c notifications:$VROD
```

then I just get an `new column` single column

**Comment by jb55** [comment]
hmm weird I can't reproduce this now. disregard

> reproduce:
> 
> ```
> ./target/release/notedeck --no-keystore --sec sec -c contacts -c notifications 
> ```
> 
> then I just get an `new column` single column

**Comment by jb55** [comment]
ohh my changes on master fixed it. that's why.

**Comment by jb55** [comment]
I've merged this into the `full_decks_support` branch with a few fixes. we can continue dev there

**Pull request closed without merging**
