### PR TITLE
Mute threads

### PR DESCRIPTION
**Pull request by ksedgwic**
Completes #214 

Is it worth caching the root_note_id somewhere in the note or note view so we don't have to recompute it more than once?

### CODE REVIEW

**Comment by jb55** [comment]
On Thu, Dec 19, 2024 at 03:48:12PM GMT, Ken Sedgwick wrote:
>
>Closes: https://github.com/damus-io/notedeck/pull/604
>---
> crates/notedeck_columns/src/actionbar.rs | 13 +++++++++----
> 1 file changed, 9 insertions(+), 4 deletions(-)
>
>diff --git a/crates/notedeck_columns/src/actionbar.rs b/crates/notedeck_columns/src/actionbar.rs
>index e8d42f0..60225e4 100644
>--- a/crates/notedeck_columns/src/actionbar.rs
>+++ b/crates/notedeck_columns/src/actionbar.rs
>@@ -7,7 +7,7 @@ use crate::{
> };
>
> use enostr::{NoteId, Pubkey, RelayPool};
>-use nostrdb::{Ndb, Transaction};
>+use nostrdb::{Ndb, NoteBuilder, Transaction};
> use notedeck::{note::root_note_id_from_selected_id, MuteFun, NoteCache, NoteRef};
>
> #[derive(Debug, Eq, PartialEq, Copy, Clone)]
>@@ -43,10 +43,15 @@ fn open_thread(
>     selected_note: &[u8; 32],
>     is_muted: &MuteFun,
> ) -> Option<NotesHolderResult> {
>-    router.route_to(Route::thread(NoteId::new(selected_note.to_owned())));
>-
>     let root_id = root_note_id_from_selected_id(ndb, note_cache, txn, selected_note);
>-    Thread::open(ndb, note_cache, txn, pool, threads, root_id, is_muted)
>+    // we only need to check if the thread is muted so use a dummy note
>+    let dummy_note = NoteBuilder::new().build().unwrap();

this seems odd to me, maybe is_muted should take an enum instead? an
enum of what its checking to mute?

>+    if is_muted(&dummy_note, root_id) {
>+        None
>+    } else {
>+        router.route_to(Route::thread(NoteId::new(selected_note.to_owned())));
>+        Thread::open(ndb, note_cache, txn, pool, threads, root_id, is_muted)
>+    }
> }
>
> impl NoteAction {

**Comment by ksedgwic** [comment]
is_muted almost always is checking everything, this is the only case where we happen to not care about any note mutes because we are already targeting the thread.

Actually, I think we should remove this check and instead display the thread view with a "this thread is muted" info warning.  Currently it crashes with something about height == 0.  But we need to handle the case where the user is sitting on a thread view and it is muted externally ... I'm guessing we currently crash in this case.

**Comment by ksedgwic** [comment]
Converted to draft to consider the thread view

**Comment by ksedgwic** [comment]
Superseded by #606

**Pull request closed without merging**
