### PR TITLE
Persist decks

### PR DESCRIPTION
**Pull request by kernelkind**
on top of #452

### CODE REVIEW

**Comment by jb55** [comment]
can you rebase and squash this into relevant commits ? it's becoming too difficult to review

**Comment by kernelkind** [comment]
> can you rebase and squash this into relevant commits ? it's becoming too difficult to review

yeah i can rebase instead of merge

**Comment by jb55** [comment]
might need a rebase instead of merge. also looks like you merged the wrong master

**Comment by jb55** [comment]
this rebase might be tricky... may need to squash a bunch of stuff first on the original base branch since there are so many edit commits

**Comment by jb55** [comment]
doesn't merge cleanly @kernelkind

**Comment by jb55** [comment]
squashed and rebased at:

`persist-decks`

but it seems to nuke my columns:

Dec02-165557
Dec02-165449

**Comment by kernelkind** [comment]
> but it seems to nuke my columns

Nuke columns generated from master? Or from columns generated in `persist_decks`? `persist_decks` uses a different serialization/deserialization method than master

**Comment by jb55** [comment]
> Nuke columns generated from master? Or from columns generated in `persist_decks`? `persist_decks` uses a different serialization/deserialization method than master

we have notedecks in the wild, we can't nuke people's desk setups

**Comment by jb55** [comment]
just waiting on the migration step so we can merge

**Comment by kernelkind** [comment]
Done:
- [x] rebased on master
- [x] separated into small commits
- [x] added new serialization technique that decouples app structure from serialized structure

Left to do:
- [ ] `columns.json` -> `decks_cache.json` migration

**Comment by jb55** [comment]
pulled everything I could into master:

```
69e93b0ebfef introduce decks_cache
35613f2e7496 ConfigureDeck & EditDeck user interfaces
83fe173ba349 appearance fixes
40a96f1df220 decks structs
```

**Comment by kernelkind** [comment]
- added metadata: `Vec<String>` field to `SerializableDeck` in `src/storage/decks.rs` in case we need more metadata besides an icon and a name.
- added deserialization for `columns.json` which won't change when our data structures change
- added logic for migration from old columns serialization to new decks serialization

**Comment by jb55** [comment]
thanks!

**Pull request merged**
