### PR TITLE
initial post reply view

### PR DESCRIPTION
**Pull request by jb55**
i spent way too much time implementing the line drawing

Xnapper-2024-06-21-14 02 59

### CODE REVIEW

**Comment by jb55** [comment]
@robagreda got it pixel perfect this time!

**Comment by kernelkind** [comment]
Looks good! But it needs a `ScrollArea` because if the note you're replying to is larger than the screen then you can't get to the post box

**Comment by jb55** [comment]
On Sat, Jun 22, 2024 at 01:53:34PM GMT, kernelkind wrote:
>Looks good! But it needs a `ScrollArea` because if the note you're replying to is larger than the screen then you can't get to the post box

good call, added

**Comment by robagreda** [comment]
This looks great @jb55 should we add a placeholder saying like: type your reply here... something like that?

**Comment by jb55** [comment]
On Mon, Jun 24, 2024 at 05:15:29PM GMT, Roberto wrote:
>This looks great @jb55 should we add a placeholder saying like: type your reply here... something like that?

yup will add this!

**Pull request merged**
