### PR TITLE
Simple Decks Impl

### PR DESCRIPTION
**Pull request by kernelkind**

### CODE REVIEW

**Comment by kernelkind** [comment]
`Decks` replaces `Columns` in `Damus`. Use `app::get_active_columns` to get the current `Columns` struct. `Columns` 'switching' happens in `app::update_damus` when the account manager performs selection to the new account (`AccountManager::perform_selection`).

This impl only adds the ability to have one `Columns` per pubkey so it isn't the full Decks implementation, but it is closer and closes #397

**Comment by kernelkind** [comment]
forgot a line, but it is ready for real this time

**Comment by ksedgwic** [comment]
Looks good to me and works on my desktop.

Is switching accounts supposed to work?  I'm having assorted errors, worth reporting?

**Comment by kernelkind** [comment]
> Is switching accounts supposed to work? I'm having assorted errors, worth reporting?

Yes it's supposed to work. What are the errors?

**Comment by ksedgwic** [comment]
Using `0082a96a875939019fa1f74ee466e72ead38beb5`:
```
rm -rf *.mdb cache ~/.config/notedeck

RUST_LOG=info cargo run --release -- --nsec <my-nsec> -c contacts -c notifications
```
- [ ] Comes up with single `Add Column` column [I'm used to seeing my stuff]
- [ ] If I ^C and then rerun (w/o deleting state) comes up w/ Contacts and Notifications as expected
- Navigate to `Add Account` and add `npub1fgz3pungsr2quse0fpjuk4c5m8fuyqx2d6a3ddqc4ek92h6hf9ns0mjeck`
- Choose Home
- [ ] See `KernelKind's Contacts` but column content is empty.  See lots of:
```
2024-11-06T00:05:02.772700Z  INFO notedeck::decks: Did not have deck for User(4a0510f26880d40e432f4865cb5714d9d3c200ca6ebb16b418ae6c555f574967), using fallback instead
2024-11-06T00:05:02.772718Z  INFO notedeck::decks: Did not have deck for User(4a0510f26880d40e432f4865cb5714d9d3c200ca6ebb16b418ae6c555f574967), using fallback instead
2024-11-06T00:05:02.772734Z  INFO notedeck::decks: Did not have deck for User(4a0510f26880d40e432f4865cb5714d9d3c200ca6ebb16b418ae6c555f574967), using fallback instead
```

**Comment by ksedgwic** [comment]
After ^C followed by restart w/o state wipe:
```
2024-11-06T00:05:49.829220Z  INFO notedeck::app: adding account: 850605096dbfb50b929e38a6c26c3d56c425325c85e05de29b759bc0e5d6cebc
2024-11-06T00:05:49.829331Z  INFO notedeck::account_manager: already have account, not adding 850605096dbfb50b929e38a6c26c3d56c425325c85e05de29b759bc0e5d6cebc
2024-11-06T00:05:49.831391Z  INFO notedeck::decks: Adding new deck for User(4a0510f26880d40e432f4865cb5714d9d3c200ca6ebb16b418ae6c555f574967)
2024-11-06T00:05:49.831675Z  INFO notedeck::decks: Adding new deck for User(850605096dbfb50b929e38a6c26c3d56c425325c85e05de29b759bc0e5d6cebc)
2024-11-06T00:05:49.837718Z  INFO notedeck::app_size_handler: wrote size [800 600]
2024-11-06T00:05:49.870517Z ERROR enostr::relay::pool: "IO error: Connection reset by peer (os error 104)"
2024-11-06T00:05:49.870581Z ERROR notedeck::app: ws://localhost:8080: IO error: Connection reset by peer (os error 104)
2024-11-06T00:05:50.084359Z  INFO ewebsock::native_tungstenite: WebSocket handshake has been successfully completed
2024-11-06T00:05:50.087351Z  INFO notedeck::app: Sending initial filters to wss://relay.damus.io
2024-11-06T00:05:50.205210Z  INFO ewebsock::native_tungstenite: WebSocket handshake has been successfully completed
2024-11-06T00:05:50.207409Z  INFO notedeck::app: Sending initial filters to wss://nostr.wine
2024-11-06T00:05:50.577468Z  INFO ewebsock::native_tungstenite: WebSocket handshake has been successfully completed
2024-11-06T00:05:50.577625Z  INFO ewebsock::native_tungstenite: WebSocket handshake has been successfully completed
2024-11-06T00:05:50.578746Z  INFO notedeck::app: Sending initial filters to wss://nos.lol
2024-11-06T00:05:50.578788Z  INFO notedeck::app: Sending initial filters to wss://purplepag.es
2024-11-06T00:05:55.047314Z ERROR enostr::relay::pool: "IO error: Connection reset by peer (os error 104)"
2024-11-06T00:05:55.047352Z ERROR notedeck::app: ws://localhost:8080: IO error: Connection reset by peer (os error 104)
2024-11-06T00:05:57.698295Z ERROR notedeck::app: poll_notes_into_view: No active subscriptions
2024-11-06T00:05:57.705694Z ERROR notedeck::app: poll_notes_into_view: No active subscriptions
2024-11-06T00:05:57.713100Z ERROR notedeck::app: poll_notes_into_view: No active subscriptions
2024-11-06T00:05:58.713780Z ERROR notedeck::app: poll_notes_into_view: No active subscriptions
```

**Comment by kernelkind** [comment]
@ksedgwic thanks for the detailed report, it helped alot. I forgot to add a column to the new user's entry in `Decks`. Bug should be fixed now, let me know if there are any other issues

**Pull request closed without merging**
